import type { Metadata } from "next";
import { DM_Sans, Inter } from "next/font/google";
import "./globals.css";
import Config from "@/config/wagmi.config";
import Navbar from "@/components/Navbar";
const dmsans = DM_Sans({
  weight: "600",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={dmsans.className}>
        <Config>
          <Navbar />
          <div className={`mt-[8px]`}>{children}</div>
        </Config>
      </body>
    </html>
  );
}
